// Original Merit Way editorial guides. Sources support the specific academic context;
// exercises and decision frameworks are our editorial suggestions.
export const guides = [
  {
    id: 'choose-masters', category: ['HIGHER EDUCATION', 'التعليم العالي'],
    title: ['Choosing a master’s that fits your next chapter', 'كيف تختار ماستر يلائم مرحلتك التالية؟'],
    intro: ['A useful shortlist begins with the work you want to do and the life you need to study around. Build the comparison before falling in love with a university name.', 'تبدأ القائمة المفيدة من العمل الذي تريد القيام به والحياة التي ستنظّم الدراسة ضمنها. ابنِ المقارنة قبل أن تتعلق باسم جامعة.'],
    sections: [
      ['Write the decision in one sentence', 'اكتب قرارك في جملة واحدة',
        'Complete this sentence: “I want this degree to help me move from … to …”. A change of profession, deeper specialist practice and preparation for research are different objectives. Pick the primary one. Then write down what would make the degree a poor fit: too much repetition, a timetable you cannot attend or too little research preparation. This makes your shortlist easier to defend.',
        'أكمل الجملة: «أريد أن تساعدني هذه الدرجة على الانتقال من… إلى…». تغيير المهنة وتعميق التخصص والاستعداد للبحث أهداف مختلفة. اختر هدفًا رئيسيًا، ثم دوّن ما قد يجعل البرنامج غير ملائم: تكرار معرفة تمتلكها، أو مواعيد لا تستطيع حضورها، أو ضعف في الإعداد البحثي. هكذا تصبح قائمتك أوضح وأقوى.'],
      ['Compare modules and assessment', 'قارن المقررات والتقييم',
        'Choose three programmes and list their required modules, optional choices, final project and assessment methods. Mark the parts that support your objective. Ask how much choice is actually available in your intake. A promising module title is less useful than knowing what you will read, produce and receive feedback on. For a future research route, investigate the research training and dissertation arrangements in particular.',
        'اختر ثلاثة برامج وسجّل المقررات الإلزامية والاختيارية والمشروع النهائي وأساليب التقييم. علّم الأجزاء التي تخدم هدفك، واسأل عن الخيارات المتاحة فعليًا في دفعتك. اسم مقرر جذاب أقل فائدة من معرفة ما ستقرأه وتنجزه وتتلقى ملاحظات عليه. وإذا كان هدفك البحث، فدقق في التدريب البحثي وترتيبات الرسالة.'],
      ['Test the timetable against a real week', 'اختبر الجدول ضمن أسبوع حقيقي',
        'Put study sessions in your calendar alongside work, care responsibilities and travel. Leave room for assessment peaks. The Open University highlights the greater independence and intensity involved in postgraduate work; use that as a prompt to ask each provider for realistic weekly expectations. For distance study, check live attendance, time zones, examinations and any required visits instead of assuming that online means fully asynchronous.',
        'ضع جلسات الدراسة في تقويمك إلى جانب العمل والمسؤوليات والتنقل، واترك مساحة لفترات تسليم الواجبات. تشير الجامعة المفتوحة إلى الاستقلالية والكثافة الأعلى في دراسة ما بعد الإجازة؛ استخدم ذلك لطلب تقدير واقعي للعبء الأسبوعي من كل جهة. وفي الدراسة عن بعد، تحقّق من الحضور المباشر والتوقيت والامتحانات والزيارات المطلوبة.'],
      ['Make a decision sheet, not a ranking', 'أنشئ ورقة قرار لا ترتيبًا عامًا',
        'Use five headings: academic fit, delivery, support, full cost and the requirements of your intended employer or next institution. Record evidence and unanswered questions beside each. Verify recognition with the relevant destination authority when it matters to your goal. Your next action is a precise enquiry to the university, with the three questions that could change your choice.',
        'استخدم خمسة محاور: الملاءمة الأكاديمية، وشكل الدراسة، والدعم، والكلفة الكاملة، ومتطلبات جهة العمل أو المؤسسة التالية. سجّل الأدلة والأسئلة المفتوحة أمام كل محور. تحقّق من الاعتراف لدى الجهة المعنية حين يكون ضروريًا لهدفك. خطوتك التالية هي استفسار دقيق للجامعة يتضمن الأسئلة الثلاثة التي قد تغيّر اختيارك.'],
    ],
    sources: [['The Open University: postgraduate workload', 'https://www.open.edu/openlearn/mod/oucontent/view.php?id=51385&section=3']],
    next: ['postgraduate.html', 'Explore higher education', 'استكشف التعليم الجامعي'],
  },
  {
    id: 'doctorate-route', category: ['DOCTORAL STUDY', 'الدراسة الدكتورالية'],
    title: ['PhD or professional doctorate: start with the research question', 'دكتوراه بحثية أم مهنية؟ ابدأ من سؤال البحث'],
    intro: ['The right doctoral route depends on the problem you want to investigate, the contribution you hope to make and the conditions in which you can sustain the work.', 'يتعلق اختيار المسار الدكتورالي بالمشكلة التي تريد بحثها والإسهام الذي تطمح إليه والظروف التي تستطيع مواصلة العمل ضمنها.'],
    sections: [
      ['Look beyond the letters', 'تجاوز اختصار اسم الدرجة',
        'A PhD commonly centres on an original research contribution. Professional doctorates such as a DBA often connect doctoral research with a field of professional practice. These are orientations, not a universal rule about every programme. Portsmouth’s DBA, for example, is framed around researching a business problem and influencing practice. Compare the actual research expectations, taught components and assessment regulations of each programme.',
        'تتمحور الدكتوراه البحثية عادة حول إسهام بحثي أصيل، بينما تربط درجات مهنية مثل DBA البحث بمجال ممارسة مهنية. هذه اتجاهات عامة وليست قاعدة لكل برنامج. فبرنامج DBA في جامعة بورتسموث، مثلًا، يركز على بحث مشكلة أعمال والتأثير في الممارسة. قارن توقعات البحث والمقررات ولوائح التقييم الفعلية لكل برنامج.'],
      ['Describe a question you can investigate', 'صِغ سؤالًا يمكنك بحثه',
        'Replace “I want to study leadership” with a bounded question about a setting, group or process. What puzzles you? What evidence could help? Why would answering it matter beyond your own experience? You do not need a finished thesis idea to begin exploring, but you do need enough specificity to identify a department and a possible supervisory fit.',
        'استبدل عبارة «أريد دراسة القيادة» بسؤال محدد يتعلق بسياق أو فئة أو عملية. ما الذي يثير تساؤلك؟ وما الأدلة التي تساعدك؟ ولماذا تهم الإجابة خارج تجربتك الشخصية؟ لا تحتاج إلى فكرة أطروحة مكتملة لتبدأ الاستكشاف، لكنك تحتاج إلى تحديد كافٍ للعثور على قسم وإشراف ملائمين.'],
      ['Check access and supervision early', 'تحقّق من البيانات والإشراف مبكرًا',
        'For a workplace-based question, ask whether the information and participants would remain accessible if your job changed. Consider confidentiality, permissions and research ethics before promising a dataset. Read prospective supervisors’ recent work and compare their methods with your interests. An attractive university name cannot replace a credible match between the project, expertise and available supervision.',
        'في السؤال المرتبط ببيئة العمل، اسأل هل ستبقى المعلومات والمشاركون متاحين إذا تغيّرت وظيفتك. فكّر في السرية والأذونات وأخلاقيات البحث قبل التعهد بالحصول على بيانات. اقرأ أعمال المشرفين المحتملين وقارن طرقهم باهتماماتك. اسم الجامعة وحده لا يعوّض التوافق بين المشروع والخبرة والإشراف المتاح.'],
      ['Compare the working conditions', 'قارن شروط العمل البحثي',
        'Build a comparison covering attendance, milestones, supervision frequency, progression reviews, full fees and your intended use of the qualification. Ask the university to clarify ambiguous points in writing. Recognition and employment expectations depend on the destination and role, so check those directly. A strong next step is a short concept note and a focused academic enquiry, not choosing solely by the title.',
        'قارن الحضور والمراحل وعدد لقاءات الإشراف ومراجعات التقدم والرسوم الكاملة واستخدامك المقصود للدرجة. اطلب توضيح النقاط الغامضة كتابيًا. تعتمد متطلبات الاعتراف والعمل على الوجهة والدور، لذا تحقّق منها مباشرة. البداية القوية هي مذكرة فكرة قصيرة واستفسار أكاديمي محدد، لا اختيار مبني على اللقب وحده.'],
    ],
    sources: [['University of Portsmouth: DBA programme', 'https://www.port.ac.uk/study/courses/postgraduate-taught/dba-professional-doctorate-in-business-administration']],
    next: ['guide-research-proposal.html', 'Prepare a research concept', 'حضّر فكرة بحثية'],
  },
  {
    id: 'research-proposal', category: ['RESEARCH PREPARATION', 'الاستعداد للبحث'],
    title: ['Turn a broad interest into a research proposal', 'حوّل اهتمامًا واسعًا إلى مقترح بحث'],
    intro: ['A proposal is a reasoned case for a project you can carry out. Use a short concept note to expose the questions you still need to answer before writing the full application.', 'المقترح حجة مدروسة لمشروع تستطيع تنفيذه. ابدأ بمذكرة فكرة قصيرة تكشف الأسئلة التي تحتاج إلى إجابتها قبل كتابة الطلب الكامل.'],
    sections: [
      ['Separate the topic from the question', 'ميّز الموضوع من السؤال',
        '“AI in education” is a topic. A question identifies what you want to understand, for whom and in what setting. Draft three possible questions, then select the one you can investigate with plausible evidence and access. Explain why the question matters in a short paragraph. Avoid promising to transform an entire sector when the proposed work concerns one bounded setting.',
        '«الذكاء الاصطناعي في التعليم» موضوع. أما السؤال فيحدد ما تريد فهمه ولمن وفي أي سياق. صغ ثلاثة أسئلة محتملة ثم اختر ما يمكن بحثه بأدلة ووصول واقعيين. اشرح أهميته في فقرة قصيرة، وتجنب الوعد بتغيير قطاع كامل بينما يتناول مشروعك سياقًا محدودًا.'],
      ['Read to position the problem', 'اقرأ لتحديد موقع المشكلة',
        'Create a reading table with four columns: source, question, method and what it leaves unresolved. Use it to compare studies instead of collecting quotations. Your first reading should help narrow the question and show how the proposed work connects to existing knowledge. Keep accurate references as you go. If you use AI to organise notes, verify every reference against the original publication.',
        'أنشئ جدول قراءة بأربعة أعمدة: المصدر والسؤال والطريقة وما بقي دون حسم. استخدمه لمقارنة الدراسات بدل جمع الاقتباسات. يجب أن تساعدك القراءة الأولى على تضييق السؤال وربط العمل المقترح بالمعرفة القائمة. احفظ المراجع بدقة، وإذا استخدمت الذكاء الاصطناعي لتنظيم الملاحظات فتحقّق من كل مرجع في منشوره الأصلي.'],
      ['Match the method to the evidence needed', 'اربط الطريقة بالأدلة المطلوبة',
        'Explain what material could answer your question and how you would obtain and analyse it. Interviews, documents and numerical data serve different purposes. Consider the practical constraints: recruitment, permissions, language, time and your own methodological preparation. Write down the most likely obstacle and a realistic alternative. This makes the proposal more credible than naming an impressive method without an access plan.',
        'اشرح المادة التي قد تجيب عن سؤالك وكيف ستجمعها وتحللها. تؤدي المقابلات والوثائق والبيانات العددية أغراضًا مختلفة. راعِ الاستقطاب والأذونات واللغة والوقت واستعدادك المنهجي. دوّن العقبة الأرجح وبديلًا واقعيًا؛ فهذا أكثر إقناعًا من تسمية طريقة متقدمة دون خطة للوصول إلى البيانات.'],
      ['Adapt to the department', 'كيّف النص مع القسم',
        'Edinburgh’s application guidance points applicants to a proposal structure and practical writing advice. Use university guidance as a starting point, then follow the exact requirements of the department or funding call you are applying to. Check length, headings, references and whether contact with a supervisor is expected. Finish by asking a reader to explain your question back to you; if they cannot, simplify it.',
        'توجّه إرشادات إدنبرة المتقدمين إلى بنية للمقترح ونصائح عملية للكتابة. استخدم إرشادات الجامعة نقطة بداية ثم اتبع متطلبات القسم أو دعوة التمويل المقصودة. راجع الطول والعناوين والمراجع وتوقعات التواصل مع مشرف. أخيرًا، اطلب من قارئ أن يشرح سؤالك بكلماته؛ فإذا تعذّر ذلك فبسّط الصياغة.'],
    ],
    sources: [['University of Edinburgh: writing a research proposal', 'https://study.ed.ac.uk/postgraduate/applying/research-degrees/proposing-own-research/writing-proposal']],
    next: ['postgraduate.html', 'Explore academic pathways', 'استكشف المسارات الأكاديمية'],
  },
  {
    id: 'project-plan', category: ['PROJECT PRACTICE', 'ممارسة المشاريع'],
    title: ['A one-page project plan that people can actually use', 'خطة مشروع من صفحة واحدة يمكن للفريق استخدامها'],
    intro: ['A useful plan makes the next decision easier. For a small launch or media project, begin with a shared definition of the result before building a detailed schedule.', 'الخطة المفيدة تجعل القرار التالي أسهل. في إطلاق صغير أو مشروع إعلامي، ابدأ بتعريف مشترك للنتيجة قبل بناء جدول مفصّل.'],
    sections: [
      ['Define what done looks like', 'عرّف معنى اكتمال العمل',
        'Write the intended result in concrete terms: a bilingual programme page approved and published by a named date, for example. List the deliverables and identify who accepts them. Keep activities separate from outcomes; “hold three meetings” says little about whether the project has succeeded. Add two or three acceptance checks so the team can recognise completion without a new debate.',
        'اكتب النتيجة بصورة ملموسة: نشر صفحة برنامج ثنائية اللغة بعد اعتمادها في موعد محدد، مثلًا. سجّل التسليمات وحدد من يقبلها. افصل الأنشطة عن النتائج؛ فـ«عقد ثلاثة اجتماعات» لا يوضح نجاح المشروع. أضف معيارين أو ثلاثة للقبول حتى يتعرف الفريق إلى الاكتمال دون نقاش جديد.'],
      ['Make scope and ownership visible', 'أظهر النطاق والمسؤوليات',
        'Name the work included in this phase and the work deferred to later. Assign one accountable owner to each deliverable, even if several people contribute. Identify the reviewer and the information they need. If a team is waiting on an expert biography or a course outline, show that dependency explicitly; hidden dependencies turn a neat timeline into a misleading promise.',
        'حدّد ما يدخل في هذه المرحلة وما يؤجّل إلى لاحقًا. عيّن مسؤولًا واضحًا عن كل تسليم ولو ساهم فيه أشخاص عدة، وحدد المراجع والمعلومات التي يحتاجها. إذا كان الفريق ينتظر نبذة خبير أو مخطط دورة فأظهر هذا الاعتماد؛ فالاعتمادات المخفية تحول الجدول المرتب إلى وعد غير واقعي.'],
      ['Plan milestones around decisions', 'خطّط المراحل حول القرارات',
        'Use a few milestones such as brief agreed, first draft reviewed, production approved and launch checked. Give each a date and a decision owner. Keep a small risk register with the risk, an early warning sign and the response. For a programme campaign, late changes to fees or start dates might require a final information check before publication.',
        'استخدم مراحل قليلة مثل اعتماد الموجز ومراجعة المسودة واعتماد الإنتاج وفحص الإطلاق. ضع لكل مرحلة موعدًا ومسؤول قرار. احتفظ بسجل مخاطر صغير يذكر الخطر وإشارة الإنذار والاستجابة. وفي حملة برنامج قد تتطلب تغييرات الرسوم أو المواعيد مراجعة نهائية للمعلومات قبل النشر.'],
      ['Use the plan in a weekly conversation', 'استخدم الخطة في مراجعة أسبوعية',
        'Review three things: what changed, what is blocked and which decision is needed next. Update the plan while the team is present. At completion, compare the delivered result with the original checks and capture one improvement for next time. The value of the page comes from maintaining a shared understanding, not from making the document look elaborate.',
        'راجع ثلاثة أمور: ما الذي تغير، وما المتعثر، وما القرار التالي المطلوب. حدّث الخطة بحضور الفريق. عند الاكتمال قارن النتيجة بمعايير القبول وسجّل تحسينًا واحدًا للمرة القادمة. تأتي قيمة الصفحة من الحفاظ على فهم مشترك، لا من جعل الوثيقة معقدة.'],
    ], sources: [], next: ['programme-project-management.html', 'Explore project management learning', 'استكشف تعلم إدارة المشاريع'],
  },
  {
    id: 'content-brief', category: ['MEDIA & COMMUNICATION', 'الإعلام والاتصال'],
    title: ['Write a programme brief before producing the campaign', 'اكتب موجز البرنامج قبل إنتاج الحملة'],
    intro: ['A good brief connects academic substance with a clear audience decision. It gives writers, designers and producers the same starting point without prescribing every creative detail.', 'يربط الموجز الجيد المضمون الأكاديمي بقرار واضح للجمهور، ويمنح الكتّاب والمصممين والمنتجين نقطة بداية مشتركة دون فرض كل التفاصيل الإبداعية.'],
    sections: [
      ['Choose one audience and one action', 'اختر جمهورًا وفعلًا واحدًا',
        'Describe a real audience situation: a working professional comparing part-time study, for example, rather than “everyone interested in education”. Identify the decision they are ready to make now. A new audience may need an explanation or a guide before being ready to enquire. Set one primary action for each piece of content so the message does not compete with itself.',
        'صِف وضعًا حقيقيًا للجمهور: مهني يقارن دراسة جزئية، مثلًا، بدل «كل المهتمين بالتعليم». حدّد القرار الذي يستعد لاتخاذه الآن. قد يحتاج الجمهور الجديد إلى شرح أو دليل قبل الاستفسار. اجعل لكل مادة فعلًا رئيسيًا واحدًا حتى لا تتنافس الرسالة مع نفسها.'],
      ['Separate the promise from the proof', 'ميّز الوعد من الدليل',
        'Write the main benefit in plain language, then list the evidence that supports it: curriculum, teaching approach, assessment, project work or a verified instructor background. Check every factual claim with the programme owner. Avoid treating a recognised institutional name as evidence for an unrelated outcome. If the creative idea depends on a claim you cannot substantiate, revise the idea before production.',
        'اكتب الفائدة الأساسية بلغة واضحة ثم اسرد أدلتها: المنهج وطريقة التدريس والتقييم والمشاريع أو خلفية مدرس موثقة. راجع كل معلومة مع صاحب البرنامج. لا تجعل اسم المؤسسة دليلًا على نتيجة لا ترتبط به. وإذا كانت الفكرة الإبداعية تعتمد على ادعاء غير موثّق فعدّلها قبل الإنتاج.'],
      ['Give the production team useful constraints', 'امنح فريق الإنتاج قيودًا مفيدة',
        'Specify the channels, formats, languages, delivery dates and approval owner. Include the essential practical details learners will ask about. For video, identify available speakers, locations and the material needed to show the learning rather than only describe it. A concise interview outline with a clear editorial purpose often helps more than a script full of promotional adjectives.',
        'حدّد القنوات والصيغ واللغات ومواعيد التسليم ومسؤول الاعتماد، وأضف المعلومات العملية التي سيسأل عنها المتعلمون. في الفيديو، حدّد المتحدثين والمواقع والمواد اللازمة لإظهار التعلم لا وصفه فقط. وقد يفيد مخطط مقابلة موجز ذو غاية تحريرية واضحة أكثر من نص مليء بالصفات الترويجية.'],
      ['Agree how you will learn from the launch', 'اتفق على طريقة التعلم من الإطلاق',
        'Choose a measure aligned with the intended action: useful enquiries, completed information requests or engagement with a detailed programme page. Review the questions people actually ask. Repeated confusion about eligibility or format is an editorial signal to improve the page. Keep a versioned brief so that later campaign pieces use the same facts and benefit from what the first release taught you.',
        'اختر مؤشرًا مرتبطًا بالفعل المقصود: استفسارات مفيدة أو طلبات معلومات مكتملة أو تفاعل مع صفحة برنامج مفصّلة. راجع أسئلة الجمهور الفعلية؛ فتكرار الغموض بشأن شروط الالتحاق أو الشكل إشارة لتحسين الصفحة. احتفظ بنسخ مؤرخة من الموجز حتى تستخدم المواد اللاحقة الحقائق نفسها وتستفيد مما كشفه الإطلاق.'],
    ], sources: [], next: ['services.html', 'Explore programme promotion services', 'استكشف خدمات ترويج البرامج'],
  },
];
