// Editorial summaries, checked against the linked provider pages on 2026-09-21.
// Portfolio exercises are Merit Way suggestions, not provider assessment claims.
export const categories = {
  ai: ['AI & work', 'الذكاء الاصطناعي والعمل'],
  marketing: ['Marketing & media', 'التسويق والإعلام'],
  data: ['Data & projects', 'البيانات والمشاريع'],
  leadership: ['Leadership & growth', 'القيادة والتطوير'],
};
// id, title, provider, platform, category, level, outcome, URL, summary, audience, topics, project
export const programmes = [
  ['google-ai', 'Google AI Essentials', 'Google', 'Google', 'ai', 'foundation', 'workflow', 'https://grow.google/ai-essentials/',
    ['Bring generative AI into everyday work with a practical introduction to prompting, productivity and responsible use.', 'أدخل الذكاء الاصطناعي التوليدي إلى عملك عبر مقدمة عملية في صياغة الطلبات والإنتاجية والاستخدام المسؤول.'],
    ['Professionals who want to use AI in routine writing, planning and information tasks without starting with programming.', 'للمهنيين الذين يريدون استخدام الذكاء الاصطناعي في الكتابة والتخطيط وتنظيم المعلومات دون البدء بالبرمجة.'],
    ['Generative AI basics; Prompt design; Reviewing outputs; Responsible workplace use', 'أساسيات الذكاء الاصطناعي التوليدي؛ صياغة الطلبات؛ مراجعة النتائج؛ الاستخدام المسؤول في العمل'],
    ['Choose a recurring planning task. Compare a manual draft with an AI-assisted version, record the edits you made and write a short quality checklist.', 'اختر مهمة تخطيط متكررة. قارن مسودة يدوية بأخرى بمساعدة الذكاء الاصطناعي، وسجّل تعديلاتك وضع قائمة قصيرة لمراجعة الجودة.']],
  ['elements-ai', 'Elements of AI: Introduction to AI', 'University of Helsinki & MinnaLearn', 'Elements of AI', 'ai', 'foundation', 'workflow', 'https://course.elementsofai.com/',
    ['Develop a clearer understanding of what AI can do, how it reasons and where its limitations matter.', 'طوّر فهمًا أوضح لقدرات الذكاء الاصطناعي وطرق الاستدلال فيه وحدوده العملية.'],
    ['Curious professionals and students who want conceptual foundations before choosing specialised AI tools or further study.', 'للمهنيين والطلاب الراغبين في بناء أساس مفاهيمي قبل اختيار أدوات متخصصة أو دراسة أعمق.'],
    ['Problem solving; Uncertainty; Machine learning; Neural networks; Social implications', 'حل المشكلات؛ عدم اليقين؛ تعلم الآلة؛ الشبكات العصبية؛ الآثار الاجتماعية'],
    ['Write a one-page assessment of an AI idea in your organisation: the problem, necessary data, expected benefit and one failure scenario.', 'اكتب تقييمًا من صفحة واحدة لفكرة ذكاء اصطناعي في مؤسستك: المشكلة والبيانات المطلوبة والفائدة المتوقعة وحالة محتملة للفشل.']],
  ['understanding-ai', 'Understanding Artificial Intelligence', 'DataCamp', 'DataCamp', 'ai', 'foundation', 'workflow', 'https://www.datacamp.com/courses/understanding-artificial-intelligence',
    ['Learn the vocabulary and business context needed to discuss AI projects with greater confidence.', 'تعرّف إلى المفاهيم والسياق العملي اللازمين لمناقشة مشاريع الذكاء الاصطناعي بثقة أكبر.'],
    ['Managers, communicators and project contributors looking for a non-technical overview of AI.', 'للمديرين والمتخصصين في الاتصال وفرق المشاريع الباحثين عن مدخل غير تقني إلى الذكاء الاصطناعي.'],
    ['AI and machine learning; Deep learning; Generative models; Organisational adoption', 'الذكاء الاصطناعي وتعلم الآلة؛ التعلم العميق؛ النماذج التوليدية؛ التبني المؤسسي'],
    ['Prepare a glossary for your team and connect each concept to a real work example. Separate a useful automation opportunity from a task needing human judgement.', 'جهّز معجمًا لفريقك واربط كل مفهوم بمثال من العمل. ميّز فرصة مناسبة للأتمتة عن مهمة تحتاج إلى حكم بشري.']],
  ['building-ai', 'Elements of AI: Building AI', 'University of Helsinki & MinnaLearn', 'Elements of AI', 'ai', 'developing', 'workflow', 'https://buildingai.elementsofai.com/',
    ['Move from AI awareness toward understanding the methods behind an AI solution and shaping an idea of your own.', 'انتقل من الوعي بالذكاء الاصطناعي إلى فهم طرق بناء الحلول وصياغة فكرة خاصة بك.'],
    ['Learners with some AI foundations who want to explore methods more deeply; programming experience helps with the coding exercises.', 'لمن يمتلك أساسًا في الذكاء الاصطناعي ويريد تعميق فهمه للطرق؛ تفيد الخبرة البرمجية في التمارين البرمجية.'],
    ['Search and optimisation; Probability; Machine learning; Neural networks; AI ideas', 'البحث والتحسين؛ الاحتمالات؛ تعلم الآلة؛ الشبكات العصبية؛ أفكار التطبيقات'],
    ['Describe an AI concept with its inputs, output, evaluation approach and an explanation of why that method fits the problem.', 'صِف فكرة تطبيق مع مدخلاته ومخرجاته وطريقة تقييمه وسبب ملاءمة الطريقة للمشكلة.']],
  ['social-media-marketing', 'Meta Social Media Marketing Professional Certificate', 'Meta', 'Coursera', 'marketing', 'foundation', 'campaign', 'https://www.coursera.org/professional-certificates/facebook-social-media-marketing',
    ['Build a structured foundation in social content, audience development and advertising campaign practice.', 'ابنِ أساسًا منظمًا في محتوى التواصل الاجتماعي وتنمية الجمهور وممارسة الحملات الإعلانية.'],
    ['Aspiring social media specialists and communicators who want to connect creative work with campaign measurement.', 'للمتخصصين الجدد في التواصل الاجتماعي والإعلاميين الذين يريدون ربط الإبداع بقياس أداء الحملات.'],
    ['Social strategy; Content planning; Advertising; Campaign measurement', 'استراتيجية التواصل؛ تخطيط المحتوى؛ الإعلان؛ قياس الحملات'],
    ['Create a sample campaign brief with one audience, one objective, three creative ideas and a measurement plan. Use a hypothetical budget before spending.', 'أنشئ موجز حملة يتضمن جمهورًا وهدفًا وثلاث أفكار إبداعية وخطة قياس. استخدم ميزانية افتراضية قبل الإنفاق.']],
  ['digital-marketing', 'Digital Marketing Certification', 'HubSpot Academy', 'HubSpot Academy', 'marketing', 'foundation', 'campaign', 'https://academy.hubspot.com/courses/digital-marketing',
    ['Connect content, search, email and social media within a coherent digital marketing approach.', 'اربط المحتوى والبحث والبريد والتواصل الاجتماعي ضمن نهج متكامل للتسويق الرقمي.'],
    ['Small teams and early-career marketers who need an overview before specialising in one channel.', 'للفرق الصغيرة والمسوقين في بداية مسيرتهم ممن يحتاجون صورة شاملة قبل التخصص في قناة واحدة.'],
    ['Digital strategy; Content; SEO; Social media; Email; Performance', 'الاستراتيجية الرقمية؛ المحتوى؛ تحسين محركات البحث؛ التواصل؛ البريد؛ الأداء'],
    ['Map the journey from discovering a programme to sending an enquiry. Assign one useful message and one success measure to each stage.', 'ارسم رحلة الجمهور من اكتشاف برنامج إلى إرسال استفسار. حدّد رسالة مفيدة ومؤشر نجاح لكل مرحلة.']],
  ['content-marketing', 'Content Marketing Certification', 'HubSpot Academy', 'HubSpot Academy', 'marketing', 'foundation', 'campaign', 'https://academy.hubspot.com/courses/content-marketing',
    ['Develop a repeatable editorial approach to useful content, storytelling and promotion.', 'طوّر نهجًا تحريريًا قابلًا للتكرار لصناعة محتوى مفيد وقصص واضحة وترويج فعال.'],
    ['Writers, media producers and communications teams building a more consistent publishing practice.', 'للكتّاب والمنتجين الإعلاميين وفرق الاتصال التي تسعى إلى ممارسة نشر أكثر اتساقًا.'],
    ['Storytelling; Content planning; Writing; Repurposing; Promotion; Measurement', 'السرد؛ تخطيط المحتوى؛ الكتابة؛ إعادة التوظيف؛ الترويج؛ القياس'],
    ['Turn one expert interview into an article outline, a short video script and three social posts. Keep the evidence and key message consistent.', 'حوّل مقابلة مع خبير إلى مخطط مقال ونص فيديو قصير وثلاث منشورات، مع الحفاظ على اتساق الأدلة والرسالة الأساسية.']],
  ['google-marketing', 'Google Digital Marketing & E-commerce Professional Certificate', 'Google', 'Coursera', 'marketing', 'foundation', 'campaign', 'https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce',
    ['Explore digital marketing and online commerce as connected parts of the customer journey.', 'استكشف التسويق الرقمي والتجارة الإلكترونية كجزأين مترابطين من رحلة العميل.'],
    ['Career starters and business teams looking for a broader route through marketing channels and e-commerce practice.', 'للمبتدئين مهنيًا وفرق الأعمال التي تبحث عن مسار أوسع في قنوات التسويق وممارسة التجارة الإلكترونية.'],
    ['Marketing channels; Email; Analytics; Online stores; Customer loyalty', 'قنوات التسويق؛ البريد؛ التحليلات؛ المتاجر الإلكترونية؛ ولاء العملاء'],
    ['Create a launch plan for a sample product or service: audience, channel mix, landing-page outline and the metrics you will review weekly.', 'أنشئ خطة إطلاق لمنتج أو خدمة افتراضية: الجمهور ومزيج القنوات ومخطط صفحة الهبوط والمؤشرات التي ستراجعها أسبوعيًا.']],
  ['project-management', 'Google Project Management Professional Certificate', 'Google', 'Coursera', 'data', 'foundation', 'project', 'https://www.coursera.org/professional-certificates/google-project-management',
    ['Build an organised approach to planning, coordinating stakeholders and delivering projects.', 'ابنِ نهجًا منظمًا لتخطيط المشاريع وتنسيق أصحاب المصلحة وتسليم النتائج.'],
    ['Project coordinators, producers and professionals moving into a role with responsibility for delivery.', 'لمنسقي المشاريع والمنتجين والمهنيين المنتقلين إلى أدوار تتحمل مسؤولية التنفيذ والتسليم.'],
    ['Project planning; Scope; Risks; Stakeholders; Agile foundations', 'تخطيط المشروع؛ النطاق؛ المخاطر؛ أصحاب المصلحة؛ أسس العمل المرن'],
    ['Build a one-page project charter for a programme launch, then add a milestone plan, risk register and a clear definition of done.', 'أنشئ ميثاق مشروع من صفحة واحدة لإطلاق برنامج، وأضف خطة للمراحل وسجل مخاطر وتعريفًا واضحًا لاكتمال العمل.']],
  ['data-analytics', 'Google Data Analytics Professional Certificate', 'Google', 'Coursera', 'data', 'foundation', 'analysis', 'https://www.coursera.org/professional-certificates/google-data-analytics',
    ['Develop a practical process for asking questions, preparing data and communicating findings.', 'طوّر منهجًا عمليًا لطرح الأسئلة وتجهيز البيانات وإيصال النتائج.'],
    ['Professionals exploring analytics and teams that need stronger evidence for everyday decisions.', 'للمهنيين الذين يستكشفون تحليل البيانات والفرق التي تحتاج أدلة أقوى في قراراتها اليومية.'],
    ['Analytical questions; Data preparation; Analysis; Visualisation; Communication', 'الأسئلة التحليلية؛ تجهيز البيانات؛ التحليل؛ التمثيل البصري؛ عرض النتائج'],
    ['Use a public dataset to answer one defined question. Document the cleaning steps and present one chart with a decision and a limitation.', 'استخدم بيانات عامة للإجابة عن سؤال محدد. وثّق خطوات التنظيف وقدّم رسمًا بيانيًا واحدًا مع قرار وحدود الاستنتاج.']],
  ['sql', 'Introduction to SQL', 'DataCamp', 'DataCamp', 'data', 'foundation', 'analysis', 'https://www.datacamp.com/courses/introduction-to-sql',
    ['Take a first step into relational data and the queries used to retrieve it.', 'ابدأ بفهم البيانات العلائقية والاستعلامات المستخدمة لاسترجاعها.'],
    ['Spreadsheet users and aspiring analysts who want to understand how information is organised in databases.', 'لمستخدمي الجداول والمحللين الجدد الذين يريدون فهم تنظيم المعلومات في قواعد البيانات.'],
    ['Relational tables; Database structure; Basic SQL queries', 'الجداول العلائقية؛ بنية قواعد البيانات؛ استعلامات SQL الأساسية'],
    ['Sketch two related tables for a course catalogue, identify their keys and write basic queries that select relevant columns.', 'ارسم جدولين مترابطين لدليل دورات، وحدّد مفاتيحهما واكتب استعلامات بسيطة لاختيار الأعمدة المطلوبة.']],
  ['python', 'Introduction to Python', 'DataCamp', 'DataCamp', 'data', 'foundation', 'analysis', 'https://www.datacamp.com/courses/intro-to-python-for-data-science',
    ['Start programming with Python through foundational syntax and data-oriented exercises.', 'ابدأ البرمجة بلغة بايثون من خلال القواعد الأساسية وتمارين مرتبطة بالبيانات.'],
    ['New programmers interested in data work and professionals who want to explore small, repeatable calculations.', 'للمبرمجين الجدد المهتمين بالبيانات والمهنيين الراغبين في استكشاف عمليات حسابية صغيرة قابلة للتكرار.'],
    ['Variables; Lists; Functions; Packages; NumPy foundations', 'المتغيرات؛ القوائم؛ الدوال؛ الحزم؛ أسس NumPy'],
    ['Create a small notebook that summarises a fictional campaign dataset. Explain each calculation in plain language alongside the code.', 'أنشئ دفترًا برمجيًا صغيرًا يلخّص بيانات حملة افتراضية، واشرح كل عملية حسابية بلغة واضحة بجانب الشيفرة.']],
  ['negotiation', 'Successful Negotiation: Essential Strategies and Skills', 'University of Michigan', 'Coursera', 'leadership', 'foundation', 'leadership', 'https://www.coursera.org/learn/negotiation-skills',
    ['Prepare for more deliberate negotiation by connecting preparation, conversation and evaluation.', 'استعد لتفاوض أكثر وعيًا يربط بين التحضير والحوار وتقييم النتيجة.'],
    ['Professionals who negotiate project scope, resources or working relationships and want a structured practice.', 'للمهنيين الذين يتفاوضون بشأن نطاق المشاريع أو الموارد أو علاقات العمل ويريدون ممارسة منظمة.'],
    ['Preparation; Negotiation strategy; Agreement; Performance evaluation', 'التحضير؛ استراتيجية التفاوض؛ الاتفاق؛ تقييم الأداء'],
    ['Prepare a role-play about a project deadline. Write down interests, alternatives and trade-offs, then review what changed after the conversation.', 'حضّر محاكاة لتفاوض على موعد تسليم مشروع. دوّن المصالح والبدائل والمقايضات ثم راجع ما تغيّر بعد الحوار.']],
  ['emotional-intelligence', 'Inspiring Leadership through Emotional Intelligence', 'Case Western Reserve University', 'Coursera', 'leadership', 'developing', 'leadership', 'https://www.coursera.org/learn/emotional-intelligence-leadership',
    ['Explore how awareness, relationships and reflection support leadership and personal change.', 'استكشف كيف يدعم الوعي والعلاقات والتأمل القيادة والتغيير الشخصي.'],
    ['Team leads and experienced contributors who want to reflect on their interactions and development.', 'لقادة الفرق والمهنيين ذوي الخبرة الراغبين في مراجعة تفاعلاتهم وتطوير ممارستهم.'],
    ['Emotional intelligence; Relationships; Mindfulness; Sustained change', 'الذكاء العاطفي؛ العلاقات؛ الانتباه الواعي؛ التغيير المستدام'],
    ['Keep a two-week reflection journal about one leadership habit. Record the situation, your response and a small adjustment to try next time.', 'احتفظ بسجل تأمل لمدة أسبوعين حول عادة قيادية واحدة. سجّل الموقف واستجابتك وتعديلًا صغيرًا لتجربته لاحقًا.']],
  ['leadership', 'Leadership and Followership', 'The Open University', 'OpenLearn', 'leadership', 'foundation', 'leadership', 'https://www.open.edu/openlearn/education-development/learning/leadership-and-followership',
    ['Look at leadership from both sides of a team relationship and develop a personal action plan.', 'انظر إلى القيادة من جانبي العلاقة داخل الفريق وطوّر خطة عمل شخصية.'],
    ['New and aspiring team leaders, and contributors who want to understand their role in a team.', 'لقادة الفرق الجدد والطامحين إلى القيادة وأعضاء الفرق الذين يريدون فهم دورهم بصورة أفضل.'],
    ['Leadership styles; Followership; Team challenges; Reflection; Development planning', 'أساليب القيادة؛ دور أعضاء الفريق؛ تحديات الفريق؛ التأمل؛ تخطيط التطوير'],
    ['Choose one common team challenge and write a short action plan with responsibilities, a review date and a sign that collaboration has improved.', 'اختر تحديًا شائعًا في الفريق واكتب خطة قصيرة تحدد المسؤوليات وموعد المراجعة وعلامة تدل على تحسّن التعاون.']],
].map(([id,title,provider,platform,category,level,outcome,url,summary,audience,topics,project]) => ({id,title,provider,platform,category,level,outcome,url,summary,audience,topics,project}));
